-- Script was generated by Devart dbForge Studio for MySQL, Version 6.0.151.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 28/02/2025 13:53:04
-- Server version: 5.6.47-log
-- Client version: 4.1

CREATE DATABASE pokemon
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

USE pokemon;

CREATE TABLE pokemon (
  PS_ID_Index int(11) NOT NULL AUTO_INCREMENT,
  PS_ID_Pokemon int(11) DEFAULT NULL,
  PS_Nome_Pokemon varchar(50) DEFAULT NULL,
  PS_Tipo_Pokemon varchar(20) DEFAULT NULL,
  PS_Poder_Pokemon decimal(15, 2) DEFAULT NULL,
  PS_Imagem_Pokemon varchar(150) DEFAULT NULL,
  PS_IMG_Pokemon varbinary(255) DEFAULT NULL,
  PRIMARY KEY (PS_ID_Index)
)
ENGINE = INNODB
AUTO_INCREMENT = 17
AVG_ROW_LENGTH = 1024
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

CREATE TABLE save_gupo (
  SaveID int(11) NOT NULL AUTO_INCREMENT,
  Data_Salvamento date DEFAULT NULL,
  Hora_Salvamento time DEFAULT NULL,
  PRIMARY KEY (SaveID)
)
ENGINE = INNODB
AUTO_INCREMENT = 49
CHARACTER SET latin1
COLLATE latin1_swedish_ci;